on:
  workflow_call:
name: Release
jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      discussions: write
      packages: write
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y git unzip tar
      - name: Install Semantic Release
        run: |
          npm install -g semantic-release \
            @semantic-release/changelog \
            @semantic-release/commit-analyzer \
            @semantic-release/exec\
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/release-notes-generator \
            conventional-changelog-conventionalcommits
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Crete Release File
        run: |
          cat << EOF > release.config.cjs
          module.exports = {
            "tagFormat": "\${version}",
            "branches": ["main"],
            "plugins": [
              "@semantic-release/changelog",
              "@semantic-release/github",
              [
                "@semantic-release/commit-analyzer",
                {
                  "preset": "conventionalcommits",
                  "releaseRules": [
                    {
                      "release": "patch",
                      "scope": "deps",
                      "type": "chore"
                    }
                  ]
                }
              ],
              [
                "@semantic-release/release-notes-generator",
                {
                  "preset": "conventionalcommits",
                  "presetConfig": {
                    "types": [
                      {
                        "section": ":rocket: Features",
                        "type": "feat"
                      },
                      {
                        "hidden": false,
                        "section": ":bug: Bug Fixes",
                        "type": "fix"
                      },
                      {
                        "hidden": false,
                        "section": ":chart_with_upwards_trend: Performance Improvements",
                        "type": "perf"
                      },
                      {
                        "hidden": false,
                        "section": ":back: Reverts",
                        "type": "revert"
                      },
                      {
                        "hidden": false,
                        "section": ":books: Documentation",
                        "type": "docs"
                      },
                      {
                        "hidden": false,
                        "section": ":ring: Styles",
                        "type": "style"
                      },
                      {
                        "hidden": false,
                        "section": ":package: Miscellaneous Chores",
                        "type": "chore"
                      },
                      {
                        "hidden": false,
                        "section": ":hammer_pick: Code Refactoring",
                        "type": "refactor"
                      },
                      {
                        "hidden": false,
                        "section": ":fingers_crossed: Tests",
                        "type": "test"
                      },
                      {
                        "hidden": false,
                        "section": ":man_construction_worker: Build System",
                        "type": "build"
                      },
                      {
                        "hidden": false,
                        "section": ":robot: Continuous Integration",
                        "type": "ci"
                      }
                    ]
                  }
                }
              ],
              [
                "@semantic-release/git",
                {
                  "assets": [
                    "CHANGELOG.md"
                  ]
                }
              ]
            ]
          }
          EOF
      - name: Release
        shell: bash
        run: semantic-release
        env:
          GH_TOKEN: ${{ github.token }}
